# Generated by Django 2.1.3 on 2018-11-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellijScanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='model_pic',
            field=models.ImageField(default='static/intellijScanner/None/no-img.jpg', upload_to='static/intellijScanner/'),
        ),
    ]
